name: build-test

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Run CI
        run: mise run ci
